spring:
  application:
    name: 'srv-neg-security-authentication-v1'
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: 'sa'
    password: '123456'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8085
  error:
    include-message: always

eureka:
  instance:
    instance-id: ${spring.application.name}:@project.version@
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8090/eureka/'

application:
  api:
    path: /srv/neg/v1/security-authentication
  secret:
    key: ''